version: '3'
services:
  workspace:
    build: .
    environment:
      PYTHONPATH: /workspace
    volumes:
      - .:/workspace
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する
  db:
    image: mysql:8.0
    # platform: linux/x86_64  # M1 Macの場合必要
    environment:
      MYSQL_DATABASE: ${DB_NAME} # 初期データベース名
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306  # ホストマシンのポート33306を、docker内のポート3306に接続する
volumes:
  mysql_data:
